const ACTIVE_BANK_PAYOUT_KEY='pocket:bank-withdraw:active'
const PREFIX='pocket:bank-withdraw:attempt:'
export type ActiveBankPayout={intentId:string;txHash:string;challengeId:string;transactionId:string;accepted:boolean;savedAt:number;owner?:string;walletAddress?:string}
function readActiveState(intentId?:string):ActiveBankPayout|null{
 try{const raw=intentId?window.localStorage.getItem(PREFIX+intentId):window.localStorage.getItem(ACTIVE_BANK_PAYOUT_KEY);const value=JSON.parse(raw||'null');if(!value?.intentId)return null;return{...value,txHash:value.txHash||'',challengeId:value.challengeId||'',transactionId:value.transactionId||'',accepted:value.accepted===true}}catch{return null}
}
function write(value:ActiveBankPayout){const current=readActiveState();const isNew=!readActiveState(value.intentId);window.localStorage.setItem(PREFIX+value.intentId,JSON.stringify(value));if(isNew||!current||current.intentId===value.intentId)window.localStorage.setItem(ACTIVE_BANK_PAYOUT_KEY,JSON.stringify(value))}
export function readActivePocketBankPayout(){return readActiveState()?.intentId||''}
export function readActivePocketBankPayoutTransfer(intentId:string){const r=readActiveState(intentId)||readActiveState();return r?.intentId===intentId?r.txHash:''}
export function readActivePocketBankPayoutAcceptance(intentId:string){const r=readActiveState(intentId)||readActiveState();return r?.intentId===intentId&&r.accepted&&r.challengeId?{challengeId:r.challengeId,transactionId:r.transactionId}:null}
export function saveActivePocketBankPayout(intentId:string,txHash='',owner?:string,walletAddress?:string){const r=readActiveState(intentId)||readActiveState();const same=r?.intentId===intentId?r:null;write({intentId,txHash:txHash||same?.txHash||'',challengeId:same?.challengeId||'',transactionId:same?.transactionId||'',accepted:same?.accepted||false,savedAt:Date.now(),owner:owner?.trim().toLowerCase()||same?.owner,walletAddress:walletAddress||same?.walletAddress})}
export function saveActivePocketBankPayoutAcceptance(intentId:string,value:{challengeId:string;transactionId:string},owner?:string,walletAddress?:string){saveActivePocketBankPayout(intentId,'',owner,walletAddress);const r=readActiveState(intentId)!;write({...r,...value,accepted:true})}
export function detachActivePocketBankPayout(intentId:string){if(readActivePocketBankPayout()===intentId)window.localStorage.removeItem(ACTIVE_BANK_PAYOUT_KEY)}
export function clearActivePocketBankPayout(intentId?:string){const id=intentId||readActivePocketBankPayout();if(id)window.localStorage.removeItem(PREFIX+id);if(!intentId||readActivePocketBankPayout()===intentId)window.localStorage.removeItem(ACTIVE_BANK_PAYOUT_KEY)}
export function readPendingBankPayouts(owner:string){const rows=new Map<string,ActiveBankPayout>();const legacy=readActiveState();if(legacy&&(!legacy.owner||legacy.owner===owner.trim().toLowerCase()))rows.set(legacy.intentId,legacy);for(let i=0;i<window.localStorage.length;i++){const k=window.localStorage.key(i);if(k?.startsWith(PREFIX)){const r=readActiveState(k.slice(PREFIX.length));if(r&&(!r.owner||r.owner===owner.trim().toLowerCase()))rows.set(r.intentId,r)}}return [...rows.values()]}
