import {expect} from 'chai'
import {ethers} from 'hardhat'
import {time,loadFixture} from '@nomicfoundation/hardhat-network-helpers'
const types={Claim:[{name:'giftId',type:'bytes32'},{name:'accountId',type:'bytes32'},{name:'recipient',type:'address'},{name:'deadline',type:'uint64'}]}
async function fixture(){
 const [sender,treasury,authority,...recipients]=await ethers.getSigners()
 const token:any=await(await ethers.getContractFactory('MockERC20')).deploy('USDC','USDC',6)
 const stock:any=await(await ethers.getContractFactory('MockERC20')).deploy('Stock','STOCK',18)
 const escrow:any=await(await ethers.getContractFactory('PocketMultiGiftEscrow')).deploy([await token.getAddress(),await stock.getAddress()],treasury.address,authority.address)
 const key=ethers.Wallet.createRandom(),salt=ethers.id('multi'),id=await escrow.giftIdFor(sender.address,salt),expiry=await time.latest()+86400
 for(const t of [token,stock]){await t.mint(sender.address,10n**22n);await t.approve(await escrow.getAddress(),ethers.MaxUint256)}
 const domain={name:'PocketMultiGift',version:'1',chainId:31337,verifyingContract:await escrow.getAddress()}
 const fund=(t=token,per=10_000_000n,count=10)=>escrow.createGift(salt,t.target,key.address,per,count,expiry)
 async function authorization(i:number,recipient=recipients[i].address){const accountId=ethers.id('account:'+i),message={giftId:id,accountId,recipient,deadline:expiry};return {message,bearer:await key.signTypedData(domain,types,message),account:await authority.signTypedData(domain,types,message)}}
 async function claim(i:number,recipient=recipients[i].address){const a=await authorization(i,recipient);return escrow.claim(id,a.message.accountId,recipient,expiry,a.bearer,a.account)}
 return {sender,treasury,authority,recipients,token,stock,escrow,key,salt,id,expiry,domain,fund,authorization,claim}
}
describe('PocketMultiGiftEscrow (local only)',()=>{
 it('funds 100 USDC once and pays exactly ten 10-USDC claims',async()=>{const f=await loadFixture(fixture);await f.fund();expect(await f.token.balanceOf(f.treasury.address)).eq(250000n);for(let i=0;i<10;i++){await f.claim(i);expect(await f.token.balanceOf(f.recipients[i].address)).eq(10_000_000n)}expect((await f.escrow.gifts(f.id)).status).eq(2);expect(await f.escrow.totalLocked(f.token.target)).eq(0);await expect(f.claim(10)).revertedWithCustomError(f.escrow,'GiftUnavailable')})
 it('rejects repeated accounts even with a different wallet, and repeated wallets with a different account',async()=>{const f=await loadFixture(fixture);await f.fund();await f.claim(0);await expect(f.claim(0,f.recipients[1].address)).revertedWithCustomError(f.escrow,'AlreadyClaimed');await expect(f.claim(1,f.recipients[0].address)).revertedWithCustomError(f.escrow,'AlreadyClaimed')})
 it('requires both signatures and binds recipient, chain and gift',async()=>{const f=await loadFixture(fixture);await f.fund();const a=await f.authorization(0);await expect(f.escrow.claim(f.id,a.message.accountId,a.message.recipient,f.expiry,a.bearer,a.bearer)).revertedWithCustomError(f.escrow,'Unauthorized');await expect(f.escrow.claim(f.id,a.message.accountId,f.recipients[1].address,f.expiry,a.bearer,a.account)).revertedWithCustomError(f.escrow,'Unauthorized');const wrong=await f.key.signTypedData({...f.domain,chainId:196},types,a.message);await expect(f.escrow.claim(f.id,a.message.accountId,a.message.recipient,f.expiry,wrong,a.account)).revertedWithCustomError(f.escrow,'Unauthorized')})
 it('refunds only unclaimed shares to sender after expiry and retains creation fee',async()=>{const f=await loadFixture(fixture);await f.fund();await f.claim(0);await f.claim(1);await expect(f.escrow.refundExpired(f.id)).revertedWithCustomError(f.escrow,'NotExpired');const before=await f.token.balanceOf(f.sender.address);await time.increaseTo(f.expiry);await expect(f.claim(2)).revertedWithCustomError(f.escrow,'Expired');await f.escrow.connect(f.recipients[0]).refundExpired(f.id);expect(await f.token.balanceOf(f.sender.address)).eq(before+80_000_000n);expect(await f.token.balanceOf(f.treasury.address)).eq(250000n);expect(await f.escrow.totalLocked(f.token.target)).eq(0);await expect(f.escrow.refundExpired(f.id)).revertedWithCustomError(f.escrow,'GiftUnavailable')})
 it('supports fixed stock quantities without USDC precision assumptions',async()=>{const f=await loadFixture(fixture);await f.fund(f.stock,10n**17n,10);await f.claim(0);expect(await f.stock.balanceOf(f.recipients[0].address)).eq(10n**17n);expect(await f.escrow.totalLocked(f.stock.target)).eq(9n*10n**17n);expect(await f.escrow.totalLocked(f.token.target)).eq(0)})
 it('rejects invalid counts, duplicate funding and unsupported tokens',async()=>{const f=await loadFixture(fixture);await expect(f.fund(f.token,1n,0)).revertedWithCustomError(f.escrow,'InvalidGift');await expect(f.fund(f.token,1n,1001)).revertedWithCustomError(f.escrow,'InvalidGift');await expect(f.escrow.createGift(f.salt,f.recipients[0].address,f.key.address,1,10,f.expiry)).revertedWithCustomError(f.escrow,'InvalidGift');await f.fund();await expect(f.fund()).revertedWithCustomError(f.escrow,'GiftExists')})
 it('settles only one competing final claim in the same block',async()=>{const f=await loadFixture(fixture);await f.fund(f.token,10_000_000n,1);const a=await f.authorization(0),b=await f.authorization(1);await ethers.provider.send('evm_setAutomine',[false]);try{const x=await f.escrow.connect(f.recipients[0]).claim(f.id,a.message.accountId,a.message.recipient,f.expiry,a.bearer,a.account,{gasLimit:500000}),y=await f.escrow.connect(f.recipients[1]).claim(f.id,b.message.accountId,b.message.recipient,f.expiry,b.bearer,b.account,{gasLimit:500000});await ethers.provider.send('evm_mine',[]);const receipts=await Promise.all([ethers.provider.getTransactionReceipt(x.hash),ethers.provider.getTransactionReceipt(y.hash)]);expect(receipts.filter(r=>r?.status===1)).length(1);expect((await f.escrow.gifts(f.id)).claimed).eq(1);expect(await f.escrow.totalLocked(f.token.target)).eq(0n)}finally{await ethers.provider.send('evm_setAutomine',[true])}})
 it('rolls back a blocked payout without consuming the account or share',async()=>{const [sender,treasury,authority,recipient]=await ethers.getSigners(),token:any=await(await ethers.getContractFactory('GiftBlockedTokenMock')).deploy(),escrow:any=await(await ethers.getContractFactory('PocketMultiGiftEscrow')).deploy([token.target],treasury.address,authority.address);await token.mint(sender.address,100250000n);await token.approve(escrow.target,100250000n);const key=ethers.Wallet.createRandom(),salt=ethers.id('blocked'),id=await escrow.giftIdFor(sender.address,salt),expiry=await time.latest()+86400,accountId=ethers.id('account');await escrow.createGift(salt,token.target,key.address,10000000n,10,expiry);const domain={name:'PocketMultiGift',version:'1',chainId:31337,verifyingContract:escrow.target},message={giftId:id,accountId,recipient:recipient.address,deadline:expiry},a=await key.signTypedData(domain,types,message),b=await authority.signTypedData(domain,types,message);await token.setBlocked(recipient.address,true);await expect(escrow.claim(id,accountId,recipient.address,expiry,a,b)).revertedWith('Blocked token account');expect(await escrow.claimedAccount(id,accountId)).eq(false);expect((await escrow.gifts(id)).claimed).eq(0);await token.setBlocked(recipient.address,false);await escrow.claim(id,accountId,recipient.address,expiry,a,b);expect((await escrow.gifts(id)).claimed).eq(1)})

})
