import {useEffect,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {foodMenu} from '../lib/foodDemo'
import '../pocket/pocketTheme.css'
import './food-demo.css'
const money=(cents:number)=>(cents/100).toFixed(2)
function savedBasket(){
 try{const saved=JSON.parse(sessionStorage.getItem('lunchroom.basket')||'null');const cart:Record<string,number>={};for(const meal of foodMenu){const quantity=saved?.cart?.[meal.id];if(Number.isInteger(quantity)&&quantity>0&&quantity<=5)cart[meal.id]=quantity}return{cart,screen:saved?.screen==='review'&&Object.keys(cart).length?'review' as const:'menu' as const}}catch{return{cart:{},screen:'menu' as const}}
}
export default function FoodDemoPage(){
 const navigate=useNavigate()
 const [cart,setCart]=useState<Record<string,number>>(()=>savedBasket().cart),[screen,setScreen]=useState<'menu'|'review'|'order'>(()=>new URLSearchParams(location.search).has('order')?'order':savedBasket().screen),[live,setLive]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[order,setOrder]=useState<any>(null)
 const lines=foodMenu.filter(m=>cart[m.id]).map(m=>({...m,quantity:cart[m.id]})),total=lines.reduce((sum,m)=>sum+m.cents*m.quantity,0),count=lines.reduce((sum,m)=>sum+m.quantity,0)
 useEffect(()=>{if(screen!=='order')try{sessionStorage.setItem('lunchroom.basket',JSON.stringify({cart,screen}))}catch{}},[cart,screen])
 const orderId=new URLSearchParams(location.search).get('order')
 useEffect(()=>{window.scrollTo(0,0)},[screen])
 async function checkOrder(){if(!orderId)return;setBusy(true);try{const r=await fetch('/api/demo/food/orders?id='+encodeURIComponent(orderId),{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Cannot check this order.');setOrder(d.order);if(d.order?.status==='paid')sessionStorage.removeItem('lunchroom.order');setScreen('order');setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{let active=true;void fetch('/api/demo/food/orders').then(r=>r.json()).then(d=>{if(active)setLive(d.liveEnabled===true)}).catch(()=>{});if(orderId){setScreen('order');void checkOrder()}return()=>{active=false}},[])
 async function pay(){setBusy(true);setError('');try{const items=lines.map(m=>({id:m.id,quantity:m.quantity})),fingerprint=JSON.stringify(items);let saved;try{saved=JSON.parse(sessionStorage.getItem('lunchroom.order')||'null')}catch{}
 const requestId=saved?.fingerprint===fingerprint&&Date.now()-saved.createdAt<25*60_000?saved.requestId:crypto.randomUUID().replace(/-/g,'');sessionStorage.setItem('lunchroom.order',JSON.stringify({fingerprint,requestId,createdAt:saved?.requestId===requestId?saved.createdAt:Date.now()}));const r=await fetch('/api/demo/food/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare',items,requestId})}),d=await r.json();if(!r.ok||!d.ok||!/^\/pay\/order\/[a-f0-9]{32}$/.test(d.checkoutUrl))throw Error(d.error||'Unable to open payment.');navigate(d.checkoutUrl)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="food-demo"><div className="food-demo-inner">
 <header className="food-header"><a href="/demo/food" className="food-logo"><span aria-hidden="true">&#10035;</span> lunchroom<span className="food-dot">.</span></a></header>
 {screen==='menu'?<><section className="food-hero"><h1>Menu</h1><p>Select items for your order.</p></section>
 <div className="food-menu-layout"><section aria-label="Menu"><div className="food-section-title"><h2>Meals</h2><span>3 items</span></div><div className="food-menu">{foodMenu.map(meal=><article className="food-meal" key={meal.id}><div className="food-art" style={{background:meal.color}} aria-hidden="true"><span>{meal.emoji}</span></div><div className="food-meal-copy"><h3>{meal.name}</h3><p>{meal.description}</p><strong>${money(meal.cents)}</strong></div><div className="food-quantity">{cart[meal.id]>0&&<><button aria-label={'Remove '+meal.name} onClick={()=>setCart({...cart,[meal.id]:Math.max(0,cart[meal.id]-1)})}>-</button><span aria-label={'Quantity '+meal.name}>{cart[meal.id]}</span></>}<button disabled={cart[meal.id]>=5} aria-label={'Add '+meal.name} onClick={()=>setCart({...cart,[meal.id]:(cart[meal.id]||0)+1})}>+</button></div></article>)}</div></section>
 <aside className="food-basket"><p className="food-eyebrow">YOUR ORDER</p><h2>{count?count+' item'+(count===1?'':'s')+' selected':'Your basket is empty'}</h2><div className="food-basket-lines">{lines.map(m=><p key={m.id}><span>{m.quantity}   {m.name}</span><b>${money(m.cents*m.quantity)}</b></p>)}</div><div className="food-total"><span>Total</span><strong>${money(total)}</strong></div><button className="food-primary" disabled={!count} onClick={()=>setScreen('review')}>Continue <span aria-hidden="true">&#8594;</span></button><p className="food-fine">USDC and tokenized stocks accepted.</p></aside></div></>:
 screen==='review'?<section className="food-payment"><button className="food-back" onClick={()=>{setScreen('menu');setError('')}}>&larr; Back to menu</button><p className="food-eyebrow">YOUR ORDER</p><h1>Review order</h1><div className="food-order-lines">{lines.map(m=><p key={m.id}><span>{m.quantity}   {m.name}</span><strong>${money(m.cents*m.quantity)}</strong></p>)}<div className="food-total"><span>Total</span><strong>${money(total)}</strong></div></div><p className="food-fine">USDC and tokenized stocks accepted.</p>{!live&&<p className="food-notice">Payments are currently unavailable.</p>}{error&&<p role="alert" className="food-error">{error}</p>}<button className="food-primary" disabled={busy||!count||!live} onClick={()=>void pay()}>{busy?'Opening Pocket...':'Pay with Pocket'}<span aria-hidden="true">&#8594;</span></button></section>:
 <section className="food-payment food-complete"><div className="food-success-mark">{order?.status==='paid'?'\u2713':' '}</div><p className="food-eyebrow">{order?.status==='paid'?'PAYMENT RECEIVED':'PAYMENT STATUS'}</p><h1>{order?.status==='paid'?'Your order is confirmed.':'Payment pending'}</h1>{order?.status==='paid'?<p>{order.amount} {order.asset} paid{order.network?' on '+(({base:'Base',arbitrum:'Arbitrum',arc:'Arc',xlayer:'X Layer'} as Record<string,string>)[order.network]||order.network):''}.<br/>Order #{order.id.slice(0,6).toUpperCase()}</p>:<p>Your payment has not been confirmed yet. Check its status below.</p>}{error&&<p role="alert" className="food-error">{error}</p>}<button className="food-primary" disabled={busy} onClick={()=>order?.status==='paid'?(setScreen('menu'),setOrder(null),setCart({}),navigate('/demo/food')):void checkOrder()}>{busy?'Checking payment ':order?.status==='paid'?'Back to menu':'Check payment status'}</button></section>}
 <footer className="food-footer"><span>Payments by <b>Hash PayLink</b></span></footer>
 </div></main>
}

