import { createElement, type HTMLAttributes } from 'react'

export function Loader2({ className = '', ...props }: HTMLAttributes<HTMLSpanElement>) {
  return createElement('span', {
    ...props,
    className: `inline-block shrink-0 animate-spin rounded-full border-2 border-current border-t-transparent motion-reduce:animate-none ${className}`,
    role: props.role ?? 'status',
  })
}
export {
  ArrowDownIcon as ArrowDownToLine,
  ArrowLeftIcon as ArrowLeft,
  ArrowLongRightIcon as ArrowRight,
  ArrowRightStartOnRectangleIcon as LogOut,
  ArrowTrendingUpIcon as TrendingUp,
  ArrowUpIcon as ArrowUpFromLine,
  ArrowUpOnSquareIcon as Share2,
  ArrowUpTrayIcon as Download,
  ArrowsRightLeftIcon as ArrowLeftRight,
  ArrowsUpDownIcon as ArrowUpDown,
  BanknotesIcon as Banknote,
  BoltIcon as Lightbulb,
  BuildingLibraryIcon as Landmark,
  BellIcon as Bell,
  CheckCircleIcon as CheckCircle2,
  CheckIcon as Check,
  ChatBubbleLeftRightIcon as MessageCircle,
  ChevronDownIcon as ChevronDown,
  ChevronLeftIcon as ChevronLeft,
  ChevronRightIcon as ChevronRight,
  ClipboardDocumentCheckIcon as CheckCheck,
  ClipboardDocumentIcon as Copy,
  ClockIcon as Clock3,
  CreditCardIcon as Wallet,
  DevicePhoneMobileIcon as Phone,
  EnvelopeIcon as Mail,
  EyeIcon as Eye,
  EyeSlashIcon as EyeOff,
  FunnelIcon as Filter,
  ExclamationCircleIcon as AlertCircle,
  ExclamationTriangleIcon as AlertTriangle,
  ArrowTopRightOnSquareIcon as ExternalLink,
  ArrowUturnLeftIcon as Undo2,
  InformationCircleIcon as Info,
  LinkIcon as Link2,
  LockClosedIcon as Lock,
  MagnifyingGlassIcon as Search,
  MoonIcon as Moon,
  PencilSquareIcon as Pencil,
  PresentationChartBarIcon as LayoutDashboard,
  CpuChipIcon as Bot,
  QueueListIcon as History,
  SignalIcon as Wifi,
  SignalIcon as Radio,
  Squares2X2Icon as Activity,
  BuildingStorefrontIcon as Store,
  SunIcon as Sun,
  TagIcon as Tag,
  TrashIcon as Trash,
  UserCircleIcon as UserRound,
  UserGroupIcon as Users,
  WrenchScrewdriverIcon as Sliders,
  XCircleIcon as XCircle,
} from '@heroicons/react/24/outline'

export { CurrencyDollarIcon as Coins, PaperAirplaneIcon as Send, TvIcon as Tv } from '@heroicons/react/24/outline'
