import PocketBankLogo from './PocketBankLogo'
import { useState } from 'react'
import { ChevronRight, Search, Star } from './PocketIcons'
import type { PocketBankRecipient } from '../hooks/usePocketBankRecipients'
export default function PocketBankRecipients({rows,busy,error,tab,onTab,onSelect,onToggle,onViewAll,onRetry,expanded=false}:{rows:PocketBankRecipient[];busy:boolean;error:string;tab:'recent'|'favourites';onTab:(tab:'recent'|'favourites')=>void;onSelect:(row:PocketBankRecipient)=>void;onToggle:(row:PocketBankRecipient)=>void;onViewAll:()=>void;onRetry:()=>void;expanded?:boolean}) {
 const [query,setQuery]=useState('')
 const filtered=rows.filter(row=>(tab==='recent'||row.favourite)&&(!query||[row.accountName,row.bankName,row.accountNumber].some(value=>value.toLowerCase().includes(query.trim().toLowerCase()))))
 const visible=expanded?filtered:filtered.slice(0,4)
 return <section className="space-y-4">
  {expanded?<label className="flex min-h-12 items-center gap-3 rounded-xl border border-gray-200 bg-white px-4 dark:border-[#262626] dark:bg-[#121212]"><Search className="h-4 w-4 shrink-0 text-gray-500 dark:text-gray-400"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search by name or account number" aria-label="Search recipients" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/></label>:<div className="flex items-center justify-between gap-3"><div role="tablist" aria-label="Bank recipients" className="flex gap-4">{(['recent','favourites'] as const).map(value=><button key={value} type="button" role="tab" aria-selected={tab===value} onClick={()=>onTab(value)} className={'min-h-11 border-b-2 text-xs font-semibold '+(tab===value?'border-gray-950 text-gray-950 dark:border-white dark:text-white':'border-transparent text-gray-500 dark:text-gray-400')}>{value==='recent'?'Recent':'Favourites'}</button>)}</div><button type="button" onClick={onViewAll} className="min-h-11 text-xs font-semibold text-gray-500 dark:text-gray-400">View all</button></div>}
  {busy&&!rows.length?<div aria-label="Loading recipients" className="space-y-5">{[0,1,2,3].map(i=><div key={i} className="flex gap-3 animate-pulse motion-reduce:animate-none"><span className="h-10 w-10 rounded-full bg-gray-200 dark:bg-white/10"/><span className="h-10 flex-1 rounded-lg bg-gray-200 dark:bg-white/10"/></div>)}</div>:visible.map(row=><div key={row.id} className="flex items-center gap-2"><button type="button" onClick={()=>onSelect(row)} className="flex min-h-20 min-w-0 flex-1 items-center gap-3 py-3 text-left"><PocketBankLogo code={row.bankCode} name={row.bankName}/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{row.accountName}</span><span className="mt-1 flex flex-wrap items-center gap-2 text-[11px] text-gray-500 dark:text-gray-400"><span className="max-w-full truncate rounded-full border border-gray-200 px-2 py-0.5 dark:border-[#262626]">{row.bankName}</span><span className="tabular-nums">{row.accountNumber}</span></span></span><ChevronRight className="h-4 w-4 shrink-0 text-gray-500"/></button><button type="button" disabled={busy} aria-label={(row.favourite?'Remove ':'Add ')+row.accountName+(row.favourite?' from favourites':' to favourites')} aria-pressed={row.favourite} onClick={()=>onToggle(row)} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-gray-500 dark:text-gray-400 disabled:opacity-40"><Star className={'h-4 w-4 '+(row.favourite?'fill-current':'')}/></button></div>)}
  {!busy&&!visible.length&&!error&&<p className="py-6 text-center text-xs text-gray-500 dark:text-gray-400">{query?'No matching recipients.':tab==='favourites'?'Your favourite recipients will appear here.':'Your recent bank transfers will appear here.'}</p>}
  {error&&<div role="alert" className="text-xs text-gray-500 dark:text-gray-400"><p>{error}</p><button type="button" onClick={onRetry} disabled={busy} className="min-h-11 font-semibold">Try again</button></div>}
 </section>
}
