import PocketBankLogo from './PocketBankLogo'
import { useState } from 'react'
import PocketBottomSheet from './PocketBottomSheet'
import { Check, ChevronDown, Search } from './PocketIcons'
export default function PocketBankPicker({value,options,onChange,disabled=false,label='Bank'}:{value:string;options:{code:string;name:string}[];onChange:(code:string,name:string)=>void;disabled?:boolean;label?:string}) {
 const [open,setOpen]=useState(false),[searching,setSearching]=useState(false),[query,setQuery]=useState('')
 const selected=options.find(bank=>bank.code===value), listed=options.filter(bank=>bank.name.toLowerCase().includes(query.trim().toLowerCase()))
 return <><button type="button" aria-label={label} aria-haspopup="dialog" aria-expanded={open} disabled={disabled} onClick={()=>{setQuery('');setSearching(false);setOpen(true)}} className="flex min-h-12 w-full items-center gap-3 rounded-xl border border-gray-200 bg-white px-3 text-left text-sm dark:border-[#262626] dark:bg-[#121212] disabled:opacity-45"><>{selected&&<PocketBankLogo code={selected.code} name={selected.name} size="selector"/>}</><span className="min-w-0 flex-1 truncate">{selected?.name||'Select ' + label.toLowerCase()}</span><ChevronDown className="h-4 w-4 text-gray-500 dark:text-gray-400"/></button>
 {open&&<PocketBottomSheet title={'Select ' + label.toLowerCase()} onClose={()=>setOpen(false)} layer={150}><h2 className="mb-4 text-lg font-bold">Select {label.toLowerCase()}</h2>{searching?<label className="mb-3 flex items-center gap-2 rounded-2xl bg-gray-50 px-3 dark:bg-white/5"><Search className="h-4 w-4 shrink-0 text-gray-500 dark:text-gray-400"/><input autoFocus aria-label={'Search ' + label.toLowerCase() + 's'} placeholder={'Search ' + label.toLowerCase() + 's'} value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/></label>:<button type="button" onClick={()=>setSearching(true)} className="mb-3 flex w-full items-center gap-2 rounded-2xl bg-gray-50 px-3 py-3 text-left text-sm text-gray-500 dark:bg-white/5 dark:text-gray-400"><Search className="h-4 w-4"/>Search {label.toLowerCase()}s</button>}<div role="listbox" aria-label={label + 's'} className="max-h-[55dvh] min-h-0 overflow-y-auto overscroll-contain">{listed.map(bank=><button type="button" role="option" aria-selected={bank.code===value} key={bank.code} onClick={()=>{onChange(bank.code,bank.name);setOpen(false)}} className="flex min-h-16 w-full items-center gap-3 rounded-2xl px-2 py-3 text-left hover:bg-gray-50 dark:hover:bg-white/5"><PocketBankLogo code={bank.code} name={bank.name}/><span className="min-w-0 flex-1 text-sm font-semibold">{bank.name}</span>{bank.code===value&&<Check className="h-4 w-4 shrink-0"/>}</button>)}{!listed.length&&<p className="py-6 text-center text-xs text-gray-500 dark:text-gray-400">{query?'No matching ' + label.toLowerCase() + 's.':label + 's are temporarily unavailable.'}</p>}</div></PocketBottomSheet>}</>
}
